import HandlesAnnouncements from './classes/HandlesAnnouncements';
import HandlesBeginChat from './classes/HandlesBeginChat';
import HandlesChat from './classes/HandlesChat';
import HandlesCharacter from './classes/HandlesCharacter';
import HandlesEnemyTarget from './classes/HandlesEnemyTarget';
import HandlesFriendlyTarget from './classes/HandlesFriendlyTarget';
import HandlesControlGame from './classes/HandlesControlGame';
import HandlesControlGameScore from './classes/HandlesControlGameScore';
import HandlesInventory from './classes/HandlesInventory';
import HandlesEquippedGear from './classes/HandlesEquippedGear';
import HandlesConsole from './classes/HandlesConsole';
import HandlesLogging from './classes/HandlesLogging';
import HandlesPlot from './classes/HandlesPlot';
declare var _default: {
    handlesAnnouncements: HandlesAnnouncements;
    handlesBeginChat: HandlesBeginChat;
    handlesChat: HandlesChat;
    handlesCharacter: HandlesCharacter;
    handlesEnemyTarget: HandlesEnemyTarget;
    handlesFriendlyTarget: HandlesFriendlyTarget;
    handlesControlGame: HandlesControlGame;
    handlesControlGameScore: HandlesControlGameScore;
    handlesInventory: HandlesInventory;
    handlesEquippedGear: HandlesEquippedGear;
    handlesConsole: HandlesConsole;
    handlesLogging: HandlesLogging;
    handlesPlot: HandlesPlot;
    on: (topic: string, callback: (info: any) => void) => any;
    off: (listener: any) => void;
    addListener: (topic: string, callback: (info: any) => void) => void;
    removeListener: (listener: any) => void;
};
export default _default;
